// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrxtrkabuasyfosmvgzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyeHRya2FidWFzeWZvc212Z3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Njc2MDYsImV4cCI6MjA2NjI0MzYwNn0.8R_KLf5QjmAXuyrUCMYBDGQZgeTCwrGmkJu7ZtcvO_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);